name: Service Build & Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'seekr/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'seekr/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
